#pragma once
static const char content[] =
"Brothers of the mine rejoice!\n"
"(Swing, swing, swing with me!)\n"
"Raise your pick and raise your voice!\n"
"(Sing, sing, sing with me!)\n"
"\n"
"Down and down into the deep\n"
"Who knows what we'll find beneath?\n"
"Diamonds, rubies, gold, and more\n"
"Hidden in the mountain store\n"
"\n"
"Born underground\n"
"Suckled from a teat of stone\n"
"Raised in the dark\n"
"The safety of our mountain home\n"
"\n"
"Skin made of iron\n"
"Steel in our bones\n"
"To dig and dig makes us free\n"
"Come on, brothers, sing with me!\n"
"\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, diggy diggy hole\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, digging a hole\n"
"\n"
"The sunlight will not reach this low\n"
"(Deep, deep in the mine)\n"
"Never seen the blue moon glow\n"
"(Dwarves won't fly so high)\n"
"\n"
"Fill a glass and down some mead\n"
"Stuff your bellies at the feast!\n"
"Stumble home and fall asleep\n"
"Dreaming in our mountain keep\n"
"\n"
"Born underground\n"
"Grown inside a rocky womb\n"
"The Earth is our cradle\n"
"The mountain shall become our tomb\n"
"\n"
"Face us on the battlefield\n"
"You will meet your doom\n"
"We do not fear what lies beneath\n"
"We can never dig too deep\n"
"\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, diggy diggy hole\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, digging a hole\n"
"\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, diggy diggy hole\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, digging a hole\n"
"\n"
"Born underground\n"
"Suckled from a teat of stone\n"
"Raised in the dark\n"
"The safety of our mountain home\n"
"\n"
"Skin made of iron\n"
"Steel in our bones\n"
"To dig and dig makes us free\n"
"Come on, brothers, sing with me!\n"
"\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, diggy diggy hole\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, digging a hole\n"
"\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, diggy diggy hole\n"
"I am a dwarf and I'm digging a hole\n"
"Diggy diggy hole, digging a hole\n\n\n";
